# Generated by Django 3.1.5 on 2021-03-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aucun', max_length=50, null=True)),
                ('year_from_bac', models.SmallIntegerField(default=0, help_text='year since the bac', verbose_name='year')),
                ('scholar_year', models.CharField(default='0000-0001', max_length=9, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.CharField(blank=True, default='...', help_text='comments of student', max_length=255, verbose_name='comments of student'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='a@a.fr', help_text='email of student', max_length=255, verbose_name='email of student'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='???', help_text='last name', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0123456789', help_text='phone number of student', max_length=10, verbose_name='phone number of student'),
        ),
        migrations.AddField(
            model_name='student',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.cursus'),
        ),
    ]
