# Generated by Django 3.1.5 on 2021-03-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_auto_20210316_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='aucun', max_length=50, null=True)),
                ('isMissing', models.BooleanField(default=0, verbose_name='Is Missing')),
                ('date', models.DateField(verbose_name='date')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.student')),
            ],
        ),
    ]
