# Generated by Django 3.1.5 on 2021-04-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_auto_20210403_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='date',
            field=models.DateField(help_text='yyyy-mm-ddd', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='appel',
            name='time_end',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='appel',
            name='time_start',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(help_text='yyyy-mm-dd', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='time_end',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='time_start',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True),
        ),
    ]
